In [1]:
from transformers import MllamaVisionModel, FlaxMllamaVisionModel
from transformers import AutoProcessor, MllamaTextModel
import requests
import torch
import jax
import jax.numpy as jnp
from PIL import Image
from huggingface_hub import login
torch.set_printoptions(precision=8)

hf_token = "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"
login(hf_token)
checkpoint = "meta-llama/Llama-3.2-11B-Vision"
processor = AutoProcessor.from_pretrained(checkpoint)
url = "https://huggingface.co/datasets/huggingface/documentation-images/resolve/0052a70beed5bf71b92610a43a52df6d286cd5f3/diffusers/rabbit.jpg"
image = Image.open(requests.get(url, stream=True).raw)
model_torch = MllamaVisionModel.from_pretrained(checkpoint, torch_dtype=torch.bfloat16)
inputs = processor(images=image, return_tensors="pt")
output_torch = model_torch(**inputs)

/opt/conda/envs/py_3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Using the `SDPA` attention implementation on multi-gpu setup with ROCM may lead to performance issues due to the FA backend. Disabling it to use alternative backends.
Loading checkpoint shards: 100%|██████████| 5/5 [00:00<00:00,  6.39it/s]


In [ ]:
model = FlaxMllamaVisionModel.from_pretrained("/home/amd/model/hub/models--meta-llama--Llama-3.2-11B-Vision/pytorch", from_pt=True, dtype=jnp.bfloat16)
inputs_jax = processor(images=image, return_tensors="jax")
output_jax = model(**inputs_jax)

5 (4, 3, 448, 448)
6 (4, 1280, 32, 32)
4 (4, 1024, 1280)


In [ ]:
output_torch['last_hidden_state']

tensor([[[[[-3.22265625e-01, -1.54687500e+00, -7.08007812e-02,  ...,
            -8.98437500e-01, -2.67187500e+00, -4.12500000e+00],
           [-4.71875000e+00,  1.92968750e+00, -7.57812500e-01,  ...,
             8.75000000e-01, -3.82812500e-01, -2.34375000e-02],
           [ 5.89843750e-01,  5.35156250e-01, -8.67187500e-01,  ...,
             1.28125000e+00,  3.43750000e-01,  1.28906250e+00],
           ...,
           [ 2.77343750e-01,  2.78125000e+00,  1.64843750e+00,  ...,
            -9.68750000e-01, -4.29687500e-02, -4.57031250e-01],
           [ 3.02734375e-01,  5.00000000e+00, -6.99218750e-01,  ...,
            -6.71875000e-01,  1.35937500e+00,  3.75000000e+00],
           [-8.12500000e-01,  1.11718750e+00,  3.14062500e+00,  ...,
            -3.45703125e-01,  1.87500000e+00,  3.87500000e+00]],

          [[-2.15625000e+00, -1.82812500e+00, -1.27343750e+00,  ...,
            -7.73437500e-01, -6.12500000e+00, -8.87500000e+00],
           [-1.52343750e+00, -5.39062500e-01,  8.90

In [ ]:
output_jax['last_hidden_state']

Array([[[[[1.19531, -1.13281, -2.125, ..., 0.699219, -0.957031, -4.75],
          [4.8125, 2.875, -2.64062, ..., -0.117188, 0.511719,
           -0.679688],
          [3.98438, 2.89062, -2.0625, ..., -1.125, 1.04688,
           -0.0742188],
          ...,
          [7.3125, -1.88281, 1.85938, ..., -0.388672, -2.09375,
           -0.621094],
          [4.1875, 0.333984, -1.3125, ..., -0.65625, -2.46875,
           -4.0625],
          [5.9375, -5.21875, -1.89062, ..., 0.191406, -1.89062,
           -2.26562]],

         [[-0.171875, 0.203125, -1.95312, ..., -0.0859375, -5.09375,
           -5.1875],
          [5.03125, 1.82031, -1.08594, ..., -0.84375, 0.90625,
           -0.28125],
          [4.90625, 1.63281, -1.15625, ..., -0.734375, 1.60938,
           0.648438],
          ...,
          [4.5625, -2.17188, 0.898438, ..., -0.441406, 0.257812,
           2.28125],
          [6.125, -1.15625, 0.664062, ..., -1.52344, -2.375, -1.64062],
          [4.28125, 3.71875, 0.546875, ..., -3.6875

In [ ]:
from jax import tree_util

def print_detailed_info(name, param):
    print(f"{name}   {param.shape}; {param.dtype}")

tree_util.tree_map_with_path(
    lambda path, x: print_detailed_info("".join(str(p) for p in path), x),
    model.params
)

['vision_model']['class_embedding']   (1280,); bfloat16
['vision_model']['gated_positional_embedding']['embedding']   (1025, 1280); bfloat16
['vision_model']['gated_positional_embedding']['gate']   (1,); bfloat16
['vision_model']['gated_positional_embedding']['tile_embedding']['embedding']   (9, 5248000); bfloat16
['vision_model']['global_transformer']['layers.0']['input_layernorm']['bias']   (1280,); bfloat16
['vision_model']['global_transformer']['layers.0']['input_layernorm']['scale']   (1280,); bfloat16
['vision_model']['global_transformer']['layers.0']['mlp']['fc1']['bias']   (5120,); bfloat16
['vision_model']['global_transformer']['layers.0']['mlp']['fc1']['kernel']   (1280, 5120); bfloat16
['vision_model']['global_transformer']['layers.0']['mlp']['fc2']['bias']   (1280,); bfloat16
['vision_model']['global_transformer']['layers.0']['mlp']['fc2']['kernel']   (5120, 1280); bfloat16
['vision_model']['global_transformer']['layers.0']['post_attention_layernorm']['bias']   (1280,); bfl

{'vision_model': {'class_embedding': None,
  'gated_positional_embedding': {'embedding': None,
   'gate': None,
   'tile_embedding': {'embedding': None}},
  'global_transformer': {'layers.0': {'input_layernorm': {'bias': None,
     'scale': None},
    'mlp': {'fc1': {'bias': None, 'kernel': None},
     'fc2': {'bias': None, 'kernel': None}},
    'post_attention_layernorm': {'bias': None, 'scale': None},
    'self_attn': {'k_proj': {'kernel': None},
     'out_proj': {'kernel': None},
     'q_proj': {'kernel': None},
     'v_proj': {'kernel': None}}},
   'layers.1': {'input_layernorm': {'bias': None, 'scale': None},
    'mlp': {'fc1': {'bias': None, 'kernel': None},
     'fc2': {'bias': None, 'kernel': None}},
    'post_attention_layernorm': {'bias': None, 'scale': None},
    'self_attn': {'k_proj': {'kernel': None},
     'out_proj': {'kernel': None},
     'q_proj': {'kernel': None},
     'v_proj': {'kernel': None}}},
   'layers.2': {'input_layernorm': {'bias': None, 'scale': None},
    

In [26]:
for name, param in model_torch.named_parameters():
    print(f"[\"{name}\"]   {param.shape}; {param.dtype}")

["class_embedding"]   torch.Size([1280]); torch.bfloat16
["patch_embedding.weight"]   torch.Size([1280, 3, 14, 14]); torch.bfloat16
["gated_positional_embedding.gate"]   torch.Size([1]); torch.bfloat16
["gated_positional_embedding.embedding"]   torch.Size([1025, 1280]); torch.bfloat16
["gated_positional_embedding.tile_embedding.weight"]   torch.Size([9, 5248000]); torch.bfloat16
["pre_tile_positional_embedding.gate"]   torch.Size([1]); torch.bfloat16
["pre_tile_positional_embedding.embedding.weight"]   torch.Size([9, 5120]); torch.bfloat16
["post_tile_positional_embedding.gate"]   torch.Size([1]); torch.bfloat16
["post_tile_positional_embedding.embedding.weight"]   torch.Size([9, 5120]); torch.bfloat16
["layernorm_pre.weight"]   torch.Size([1280]); torch.bfloat16
["layernorm_pre.bias"]   torch.Size([1280]); torch.bfloat16
["layernorm_post.weight"]   torch.Size([1280]); torch.bfloat16
["layernorm_post.bias"]   torch.Size([1280]); torch.bfloat16
["transformer.layers.0.self_attn.q_proj.we

In [51]:
model_torch.state_dict()["transformer.layers.0.self_attn.o_proj.weight"] 

tensor([[ 0.01098633, -0.02966309, -0.00343323,  ..., -0.00169373,
          0.01062012,  0.01806641],
        [-0.02636719,  0.00051880,  0.01574707,  ..., -0.02087402,
         -0.00775146,  0.01440430],
        [ 0.02624512,  0.01470947,  0.00355530,  ...,  0.03149414,
          0.01428223, -0.03369141],
        ...,
        [ 0.00500488,  0.02160645, -0.01123047,  ...,  0.02722168,
         -0.02355957,  0.01165771],
        [ 0.00964355,  0.02209473,  0.02966309,  ...,  0.01611328,
         -0.02160645, -0.00793457],
        [ 0.00393677,  0.00271606,  0.01049805,  ...,  0.00646973,
          0.02551270, -0.01989746]], dtype=torch.bfloat16)

In [53]:
model.params['vision_model']['transformer']['layers.0']['self_attn']['out_proj']['kernel'].transpose((1, 0))

Array([[ 0.0095253 ,  0.00216762, -0.00734951, ...,  0.01043756,
        -0.01556316,  0.03573614],
       [-0.00832118,  0.00039678,  0.00667837, ..., -0.01705111,
        -0.00839255, -0.00744995],
       [ 0.00305349, -0.01669949, -0.00457204, ...,  0.00687982,
         0.00614593, -0.0055537 ],
       ...,
       [-0.00885951, -0.00997591, -0.00521528, ...,  0.02455697,
        -0.00221298, -0.00605446],
       [ 0.02340402, -0.00848565, -0.01148236, ..., -0.00345229,
        -0.02129878,  0.00617719],
       [-0.00339484, -0.00202657,  0.01270217, ...,  0.00217399,
         0.00515973,  0.00073385]], dtype=float32)