In [ ]:
from transformers import MllamaVisionModel, FlaxMllamaVisionModel
from transformers import AutoProcessor, MllamaTextModel
import requests
import torch
import jax
import jax.numpy as jnp
from PIL import Image
from huggingface_hub import login
torch.set_printoptions(precision=8)
jax.numpy.set_printoptions(precision=10)
import os
os.environ['XLA_PYTHON_CLIENT_MEM_FRACTION'] = '0.5'

hf_token = "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"
login(hf_token)
checkpoint = "meta-llama/Llama-3.2-11B-Vision"
processor = AutoProcessor.from_pretrained(checkpoint)
url = "https://huggingface.co/datasets/huggingface/documentation-images/resolve/0052a70beed5bf71b92610a43a52df6d286cd5f3/diffusers/rabbit.jpg"
image = Image.open(requests.get(url, stream=True).raw)

model_torch = MllamaVisionModel.from_pretrained(checkpoint, torch_dtype=torch.bfloat16).to("cuda")

model = FlaxMllamaVisionModel.from_pretrained("/home/amd/model/hub/models--meta-llama--Llama-3.2-11B-Vision/pytorch", from_pt=True, dtype=jnp.bfloat16)

/opt/conda/envs/py_3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Using the `SDPA` attention implementation on multi-gpu setup with ROCM may lead to performance issues due to the FA backend. Disabling it to use alternative backends.
Loading checkpoint shards: 100%|██████████| 5/5 [00:01<00:00,  4.75it/s]
2024-11-25 21:56:09.938396: W external/xla/xla/tsl/framework/bfc_allocator.cc:497] Allocator (GPU_0_bfc) ran out of memory trying to allocate 180.18MiB (rounded to 188928000)requested by op 
2024-11-25 21:56:09.938504: W external/xla/xla/tsl/framework/bfc_allocator.cc:508] ****************xxxxx**************************************************xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
E1125 21:56:09.938525 1386435 pjrt_stream_executor_client.cc:3084] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of me

XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 188928000 bytes.

: 

In [ ]:
inputs_jax = processor(images=image, return_tensors="jax")
inputs = processor(images=image, return_tensors="pt").to("cuda")
output_torch = model_torch(**inputs)

torch torch.Size([1, 4128, 1280]) tensor([[[-0.25195312, -0.06542969, -0.02661133,  ...,  0.25781250,
          -0.01263428,  0.31054688],
         [-0.33007812, -0.01623535,  0.09814453,  ...,  0.22167969,
          -0.09863281,  0.48046875],
         [-0.34179688, -0.02038574,  0.11181641,  ...,  0.22070312,
          -0.10449219,  0.47656250],
         ...,
         [-0.53906250,  0.02600098,  0.16503906,  ...,  0.17773438,
          -0.05615234, -0.05346680],
         [-0.53906250,  0.02600098,  0.16503906,  ...,  0.17773438,
          -0.05615234, -0.05346680],
         [-0.53906250,  0.02600098,  0.16503906,  ...,  0.17773438,
          -0.05615234, -0.05346680]]], device='cuda:0', dtype=torch.bfloat16,
       grad_fn=<UnsafeViewBackward0>)
torch torch.Size([1, 4128, 1280]) tensor([[[-0.05151367, -0.01531982, -0.06152344,  ...,  0.02380371,
           0.09423828, -0.00494385],
         [-0.18066406, -0.01855469, -0.04980469,  ...,  0.06396484,
           0.29882812, -0.05273438],

In [ ]:
output_jax = model(**inputs_jax)

jax (1, 4128, 1280) [[[-0.253906 -0.0654297 -0.0266113 ... 0.255859 -0.0126343 0.310547]
  [-0.330078 -0.0166016 0.0986328 ... 0.22168 -0.0991211 0.480469]
  [-0.341797 -0.0205078 0.111816 ... 0.220703 -0.104492 0.476562]
  ...
  [-0.539062 0.0266113 0.165039 ... 0.178711 -0.0561523 -0.0537109]
  [-0.539062 0.0266113 0.165039 ... 0.178711 -0.0561523 -0.0537109]
  [-0.539062 0.0266113 0.165039 ... 0.178711 -0.0561523 -0.0537109]]]
jax (1, 4128, 1280) [[[-0.0515137 -0.0154419 -0.060791 ... 0.0239258 0.09375 -0.00466919]
  [-0.181641 -0.0186768 -0.0498047 ... 0.0639648 0.298828 -0.0529785]
  [-0.193359 -0.0236816 -0.0301514 ... 0.0600586 0.341797 -0.0429688]
  ...
  [0.057373 -0.000492096 -0.195312 ... -0.074707 0.114746 -0.118652]
  [0.057373 -0.000492096 -0.195312 ... -0.074707 0.114746 -0.118652]
  [0.057373 -0.000492096 -0.195312 ... -0.074707 0.114746 -0.118652]]]
jax (1, 4128, 1280) [[[-0.0291748 0.10498 -0.0625 ... 0.0383301 -0.109863 -0.176758]
  [-0.0311279 -0.0493164 -0.109375 .

In [2]:
x = (1, None)
x[1]

In [27]:
attention_mask = inputs["aspect_ratio_mask"].reshape(1, -1)
torch_arr = _prepare_aspect_ratio_attention_mask_torch(
            aspect_ratio_mask=attention_mask, # (batch_size * num_concurrent_media, 4)
            num_patches=1025, # 1025 = 1024+1
            target_length=1032, # 1032
            dtype=torch.float16,
        )

In [28]:
attention_mask = inputs_jax["aspect_ratio_mask"].reshape(1, -1)
jax_arr = _prepare_aspect_ratio_attention_mask_jax(
            aspect_ratio_mask=attention_mask, # (batch_size * num_concurrent_media, 4)
            num_patches=1025, # 1025 = 1024+1
            target_length=1032, # 1032
            dtype=jnp.float32,
        )

In [29]:
are_equivalent(torch_arr, jax_arr)

False

In [30]:
torch_arr

tensor([[[[     0.,      0.,     -0.,  ...,      0.,     -0.,     -0.],
          [     0.,      0.,     -0.,  ...,      0.,     -0.,     -0.],
          [     0.,      0.,     -0.,  ...,      0.,     -0.,     -0.],
          ...,
          [     0.,      0.,     -0.,  ..., -65504., -65504., -65504.],
          [     0.,      0.,     -0.,  ..., -65504., -65504., -65504.],
          [     0.,      0.,     -0.,  ..., -65504., -65504., -65504.]]]],
       device='cuda:0', dtype=torch.float16)

In [31]:
jax_arr

Array([[[[-0.0000000e+00, -0.0000000e+00, -0.0000000e+00, ...,
          -0.0000000e+00, -0.0000000e+00, -0.0000000e+00],
         [-0.0000000e+00, -0.0000000e+00, -0.0000000e+00, ...,
          -0.0000000e+00, -0.0000000e+00, -0.0000000e+00],
         [-0.0000000e+00, -0.0000000e+00, -0.0000000e+00, ...,
          -0.0000000e+00, -0.0000000e+00, -0.0000000e+00],
         ...,
         [-0.0000000e+00, -0.0000000e+00, -0.0000000e+00, ...,
          -3.4028235e+38, -3.4028235e+38, -3.4028235e+38],
         [-0.0000000e+00, -0.0000000e+00, -0.0000000e+00, ...,
          -3.4028235e+38, -3.4028235e+38, -3.4028235e+38],
         [-0.0000000e+00, -0.0000000e+00, -0.0000000e+00, ...,
          -3.4028235e+38, -3.4028235e+38, -3.4028235e+38]]]],      dtype=float32)

In [8]:
inputs['aspect_ratio_mask']

tensor([[[1, 1, 1, 1]]], device='cuda:0')

In [3]:
output_torch.last_hidden_state[0,0,0,0,-10:]

tensor([-0.53125000,  0.47265625, -0.35742188,  0.23925781, -2.00000000,
        -0.24902344,  0.36718750, -0.90625000, -2.68750000, -4.12500000],
       device='cuda:0', dtype=torch.bfloat16, grad_fn=<SliceBackward0>)

In [4]:
output_jax.last_hidden_state[0,0,0,0,-10:]

Array([-0.554688, 0.332031, -0.0800781, 4.34375, 7.125, -0.386719,
       0.636719, -0.601562, -0.289062, -0.617188], dtype=bfloat16)

In [5]:
from transformers import MllamaVisionModel, FlaxMllamaVisionModel
from transformers import AutoProcessor, MllamaTextModel
import requests
import torch
import jax
import jax.numpy as jnp
from PIL import Image
from huggingface_hub import login
torch.set_printoptions(precision=8)

hf_token = "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"
login(hf_token)
checkpoint = "meta-llama/Llama-3.2-11B-Vision"
processor = AutoProcessor.from_pretrained(checkpoint)
url = "https://huggingface.co/datasets/huggingface/documentation-images/resolve/0052a70beed5bf71b92610a43a52df6d286cd5f3/diffusers/rabbit.jpg"
image = Image.open(requests.get(url, stream=True).raw)
inputs_torch = processor(images=image, return_tensors="pt")
inputs_jax = processor(images=image, return_tensors="jax")

In [6]:
import torch.nn as nn
import torch
class TorchConv(nn.Module):
    def __init__(self, dtype=torch.bfloat16):
        super(TorchConv, self).__init__()
        self.patch_embedding = nn.Conv2d(
            in_channels=3, #3
            out_channels=1280, #1280
            kernel_size=14, #14
            stride=14, #14
            padding="valid",
            bias=False,
            dtype=dtype,
        )
        self.dtype = dtype

    def forward(
        self,
        pixel_values: torch.Tensor,

    ):
        batch_size, num_concurrent_media, num_tiles, num_channels, height, width = pixel_values.shape #(1, 1, 4, 3, 448, 448)

        pixel_values = pixel_values.reshape(batch_size * num_concurrent_media * num_tiles, num_channels, height, width) #(4, 3, 448, 448)
        # Patch embedding
        patch_embeds = self.patch_embedding(pixel_values.to(torch.bfloat16).to('cuda')) # (batch_size * num_concurrent_media * num_tiles, hidden_size=1280, 32, 32)
        return patch_embeds


# Initialize the model
torch_model = TorchConv(dtype=torch.bfloat16).to('cuda')


# Get the parameters from the TorchConv model
torch_params = torch_model.patch_embedding.weight
# # Example PyTorch tensor
# torch_params_32 = torch.randn(torch_params.shape, dtype=torch.float32)

# # Permute the tensor's dimensions
# torch_params_permuted = torch_params_32.permute(2, 3, 1, 0)

# # Convert the PyTorch tensor to a NumPy array
# torch_params_numpy = torch_params_permuted.detach().cpu().numpy()

# # Convert the NumPy array to a JAX tensor with dtype bfloat16
# jax_params = jnp.array(torch_params_numpy, dtype=jnp.bfloat16)
# torch_params = torch.tensor(torch_params_32, dtype=torch.bfloat16)
# torch_params = torch.nn.Parameter(torch.tensor(torch_params_32, dtype=torch.bfloat16, device='cuda'))
# torch_model.patch_embedding.weight = torch_params
torch_model.patch_embedding.weight = model_torch.patch_embedding.weight
# Perform a forward pass through the model
output_torch = torch_model(inputs_torch.pixel_values)

In [7]:
from flax.core import freeze, unfreeze
from flax import linen as fnn
class JaxConv(fnn.Module):
  dtype: jnp.dtype = jnp.bfloat16

  def setup(self):

    self.patch_embedding = fnn.Conv(
        1280,
        kernel_size=(14, 14),
        strides=(14, 14),
        padding="VALID",
        use_bias=False,
        dtype=self.dtype,
        kernel_init=jax.nn.initializers.normal(),
    )
 
  def __call__(
      self,
      pixel_values: jnp.ndarray,
  ):
        batch_size, num_concurrent_media, num_tiles, num_channels, height, width = pixel_values.shape

        pixel_values = pixel_values.reshape((batch_size * num_concurrent_media * num_tiles, num_channels, height, width))

        # Patch embedding
        patch_embeds = self.patch_embedding(pixel_values.transpose((0, 2, 3, 1)))

        patch_embeds = patch_embeds.transpose((0, 3, 1, 2))

        return patch_embeds
        
# Initialize the model
flax_model = JaxConv()
# Initialize parameters
params = flax_model.init(jax.random.PRNGKey(0), jnp.ones((1, 1, 4, 3, 448, 448)))

# # Convert PyTorch parameters to JAX parameters
params = unfreeze(params)
params['params']['patch_embedding']['kernel'] = model.params['vision_model']['patch_embedding']['kernel']
params = freeze(params)


In [8]:
output_jax = flax_model.apply(params, inputs_jax.pixel_values)

In [9]:
output_jax

Array([[[[-0.191406, -0.176758, -0.185547, ..., -0.175781, -0.174805,
          -0.0688477],
         [0.00186157, -0.0678711, -0.234375, ..., -0.175781, -0.172852,
          -0.170898],
         [0.0534668, 0.114258, 0.0119629, ..., -0.203125, -0.191406,
          -0.192383],
         ...,
         [0.0219727, 0.0603027, 0.0556641, ..., -0.0135498, -0.0859375,
          -0.121582],
         [0.034668, 0.103516, 0.032959, ..., 0.00430298, 0.010376,
          -0.111328],
         [0.0181885, 0.0126953, 0.00482178, ..., 0.0419922, 0.0241699,
          -0.0947266]],

        [[0.0412598, 0.0356445, 0.0444336, ..., 0.0368652, 0.0410156,
          0.176758],
         [0.12207, 0.0373535, 0.090332, ..., 0.0291748, 0.0358887,
          0.0664062],
         [-0.0280762, 0.0534668, -0.0334473, ..., 0.0456543, 0.0317383,
          0.0152588],
         ...,
         [-0.0566406, 0.0668945, 0.0385742, ..., 0.0158691, -0.022583,
          0.0622559],
         [0.0108032, 0.0429688, 0.0495605, ..., 

In [10]:
output_torch

tensor([[[[-1.91406250e-01, -1.76757812e-01, -1.85546875e-01,  ...,
           -1.75781250e-01, -1.74804688e-01, -6.88476562e-02],
          [ 1.86157227e-03, -6.78710938e-02, -2.34375000e-01,  ...,
           -1.75781250e-01, -1.72851562e-01, -1.70898438e-01],
          [ 5.34667969e-02,  1.14257812e-01,  1.19628906e-02,  ...,
           -2.03125000e-01, -1.91406250e-01, -1.92382812e-01],
          ...,
          [ 2.19726562e-02,  6.03027344e-02,  5.56640625e-02,  ...,
           -1.35498047e-02, -8.59375000e-02, -1.21582031e-01],
          [ 3.46679688e-02,  1.03515625e-01,  3.29589844e-02,  ...,
            4.30297852e-03,  1.03759766e-02, -1.11328125e-01],
          [ 1.81884766e-02,  1.26953125e-02,  4.82177734e-03,  ...,
            4.19921875e-02,  2.41699219e-02, -9.47265625e-02]],

         [[ 4.12597656e-02,  3.56445312e-02,  4.44335938e-02,  ...,
            3.68652344e-02,  4.10156250e-02,  1.76757812e-01],
          [ 1.22070312e-01,  3.73535156e-02,  9.03320312e-02,  ...

In [11]:
inputs_jax.pixel_values[0,0,0,0,:10,:10]

Array([[1.5507771, 1.477785 , 1.4047928, 1.3172023, 1.2442101, 1.2296118,
        1.2442101, 1.2442101, 1.273407 , 1.273407 ],
       [1.5215802, 1.4631865, 1.3901944, 1.3172023, 1.2442101, 1.2296118,
        1.2442101, 1.2442101, 1.273407 , 1.273407 ],
       [1.5069818, 1.4339896, 1.3609976, 1.2880055, 1.2296118, 1.2296118,
        1.2442101, 1.2442101, 1.273407 , 1.273407 ],
       [1.477785 , 1.3901944, 1.3172023, 1.2442101, 1.2150133, 1.2296118,
        1.2442101, 1.2442101, 1.273407 , 1.273407 ],
       [1.4047928, 1.3463992, 1.3026038, 1.2442101, 1.2150133, 1.2296118,
        1.2442101, 1.2442101, 1.273407 , 1.273407 ],
       [1.3318007, 1.3026038, 1.2880055, 1.273407 , 1.273407 , 1.2588086,
        1.2588086, 1.2588086, 1.2880055, 1.2880055],
       [1.2880055, 1.2880055, 1.2880055, 1.2880055, 1.2880055, 1.273407 ,
        1.273407 , 1.273407 , 1.2880055, 1.2880055],
       [1.2880055, 1.2880055, 1.2880055, 1.2880055, 1.2880055, 1.273407 ,
        1.273407 , 1.273407 , 1.28800

In [12]:
model_torch.named_modules()

<generator object Module.named_modules at 0x7ef9b8d478b0>

In [13]:
i = 0
output_torch['last_hidden_state'][:, :, :, 0, i:(i+10)]

IndexError: too many indices for tensor of dimension 4

In [ ]:
output_jax1['last_hidden_state'][:, :, :, 0, i:(i+10)]

Array([[[[5.65625, -5.25, -5.375, 5.8125, 4.90625, -4.21875, 1.55469,
          -3.15625, 0.984375, 3.90625],
         [6.34375, -3.03125, -6.4375, 6.03125, 7.8125, -3.59375,
          2.48438, -7.15625, -0.753906, 4.1875],
         [14, -4.09375, -7.625, 2.76562, 11.8125, -10.5, 0.722656,
          -6.59375, 0.808594, 5.59375],
         [4.21875, 3.5, -2.51562, -3.89062, -1.25, 0.566406, 4.65625,
          2.09375, 8.8125, 4.5625]]]], dtype=bfloat16)

In [ ]:
output_jax2['last_hidden_state'][:, :, :, 0, i:(i+10)]

Array([[[[5.65625, -5.25, -5.375, 5.8125, 4.90625, -4.21875, 1.55469,
          -3.15625, 0.984375, 3.90625],
         [6.34375, -3.03125, -6.4375, 6.03125, 7.8125, -3.59375,
          2.48438, -7.15625, -0.753906, 4.1875],
         [14, -4.09375, -7.625, 2.76562, 11.8125, -10.5, 0.722656,
          -6.59375, 0.808594, 5.59375],
         [4.21875, 3.5, -2.51562, -3.89062, -1.25, 0.566406, 4.65625,
          2.09375, 8.8125, 4.5625]]]], dtype=bfloat16)

In [ ]:
from jax import tree_util

def print_detailed_info(name, param):
    print(f"{name}   {param.shape}; {param.dtype}")

tree_util.tree_map_with_path(
    lambda path, x: print_detailed_info("".join(str(p) for p in path), x),
    model.params
)

In [ ]:
for name, param in model_torch.named_parameters():
    print(f"[\"{name}\"]   {param.shape}; {param.dtype}")

In [ ]:
model_torch.state_dict()["transformer.layers.31.self_attn.q_proj.weight"] 

In [ ]:
model.params['vision_model']['transformer']['layers.31']['self_attn']['q_proj']['kernel']

In [ ]:
inputs_jax['pixel_values'].shape

In [ ]:
inputs_jax['pixel_values'].shape