In [ ]:
from transformers import MllamaVisionModel, FlaxMllamaVisionModel
from transformers import AutoProcessor, MllamaTextModel
import requests
import torch
import jax
import jax.numpy as jnp
from PIL import Image
from huggingface_hub import login
torch.set_printoptions(precision=8)

hf_token = "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"
login(hf_token)
checkpoint = "meta-llama/Llama-3.2-11B-Vision"
processor = AutoProcessor.from_pretrained(checkpoint)
url = "https://huggingface.co/datasets/huggingface/documentation-images/resolve/0052a70beed5bf71b92610a43a52df6d286cd5f3/diffusers/rabbit.jpg"
image = Image.open(requests.get(url, stream=True).raw)
model_torch = MllamaVisionModel.from_pretrained(checkpoint, torch_dtype=torch.bfloat16).to("cuda")
model = FlaxMllamaVisionModel.from_pretrained("/home/amd/model/hub/models--meta-llama--Llama-3.2-11B-Vision/pytorch", from_pt=True, dtype=jnp.bfloat16)

/opt/conda/envs/py_3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Using the `SDPA` attention implementation on multi-gpu setup with ROCM may lead to performance issues due to the FA backend. Disabling it to use alternative backends.
Loading checkpoint shards: 100%|██████████| 5/5 [00:00<00:00,  6.54it/s]


(1, 4, 1024, 1280)
[[[[-2.24609375e-01 -6.98852539e-03 -1.17187500e-01 ... -1.09863281e-01
     1.04492188e-01  3.16406250e-01]
   [ 1.50390625e-01  9.76562500e-02 -1.98242188e-01 ... -3.90625000e-01
     1.85546875e-01 -3.39843750e-01]
   [ 1.81640625e-01 -2.15820312e-01 -1.89453125e-01 ...  3.60107422e-03
     3.33984375e-01 -1.80664062e-01]
   ...
   [ 1.01562500e-01  1.02050781e-01 -7.47070312e-02 ... -1.39648438e-01
     1.03027344e-01  1.31225586e-03]
   [ 2.02148438e-01 -2.55859375e-01 -2.59765625e-01 ...  1.70898438e-01
     4.12597656e-02 -3.37890625e-01]
   [ 5.31250000e-01  4.90722656e-02  4.47265625e-01 ... -2.71484375e-01
     1.69921875e-01  7.66601562e-02]]

  [[ 3.41796875e-01 -1.49414062e-01 -1.13769531e-01 ...  2.89062500e-01
     3.12500000e-01  3.12500000e-02]
   [ 3.60107422e-03 -8.34960938e-02 -3.95507812e-02 ... -1.24511719e-01
    -3.51562500e-02  1.26953125e-01]
   [ 6.83593750e-01  4.47265625e-01 -4.43359375e-01 ...  5.66406250e-02
    -3.80859375e-01  3.22265

E1122 23:03:36.206106  967933 buffer_comparator.cc:157] Difference at 19685: -inf, expected -2.88442e+38
E1122 23:03:36.206142  967933 buffer_comparator.cc:157] Difference at 20777: -inf, expected -3.37624e+38
E1122 23:03:36.206146  967933 buffer_comparator.cc:157] Difference at 20867: 2.96418e+38, expected inf
E1122 23:03:36.206148  967933 buffer_comparator.cc:157] Difference at 20965: -inf, expected -3.04393e+38
E1122 23:03:36.206151  967933 buffer_comparator.cc:157] Difference at 21049: 2.89772e+38, expected inf
E1122 23:03:36.206242  967933 buffer_comparator.cc:157] Difference at 83233: inf, expected 3.12369e+38
E1122 23:03:36.206245  967933 buffer_comparator.cc:157] Difference at 83283: -inf, expected -3.16356e+38
E1122 23:03:36.206248  967933 buffer_comparator.cc:157] Difference at 83325: inf, expected 6.18091e+37
E1122 23:03:36.206250  967933 buffer_comparator.cc:157] Difference at 83399: 2.21981e+38, expected inf
E1122 23:03:36.206252  967933 buffer_comparator.cc:157] Differenc

In [ ]:
inputs_jax = processor(images=image, return_tensors="jax")
inputs = processor(images=image, return_tensors="pt").to("cuda")
output_torch = model_torch(**inputs)
output_jax = model(**inputs_jax)


torch.Size([1, 4, 1024, 1280])
tensor([[[[-1.85546875e-01, -7.61718750e-02, -1.38671875e-01,  ...,
           -5.11718750e-01, -1.50390625e-01, -2.49023438e-02],
          [-1.70898438e-01, -8.15429688e-02, -3.30078125e-01,  ...,
           -4.72656250e-01, -4.41406250e-01, -6.25000000e-02],
          [-1.79687500e-01, -7.27539062e-02, -4.29687500e-01,  ...,
           -4.64843750e-01, -3.45703125e-01, -6.93359375e-02],
          ...,
          [ 4.78515625e-02, -1.92382812e-01,  1.59179688e-01,  ...,
            2.61718750e-01,  6.40625000e-01, -2.59765625e-01],
          [ 2.99072266e-02, -1.23535156e-01,  9.27734375e-02,  ...,
            1.87500000e-01,  1.31250000e+00, -1.91406250e-01],
          [-8.88671875e-02, -1.46484375e-03,  1.70898438e-01,  ...,
           -1.66015625e-01,  2.48437500e+00, -8.10546875e-02]],

         [[-1.29882812e-01,  6.34765625e-02, -9.57031250e-01,  ...,
           -5.42968750e-01,  4.23828125e-01, -3.32031250e-02],
          [-1.85546875e-01,  6.5429

In [10]:
output_torch.last_hidden_state[0,0,0,0,-10:]

tensor([-0.53125000,  0.47265625, -0.35742188,  0.23925781, -2.00000000,
        -0.24902344,  0.36718750, -0.90625000, -2.68750000, -4.12500000],
       device='cuda:0', dtype=torch.bfloat16, grad_fn=<SliceBackward0>)

In [11]:
output_jax.last_hidden_state[0,0,0,0,-10:]

Array([-0.554688, 0.332031, -0.0800781, 4.34375, 7.125, -0.386719,
       0.636719, -0.601562, -0.289062, -0.617188], dtype=bfloat16)

In [6]:
from transformers import MllamaVisionModel, FlaxMllamaVisionModel
from transformers import AutoProcessor, MllamaTextModel
import requests
import torch
import jax
import jax.numpy as jnp
from PIL import Image
from huggingface_hub import login
torch.set_printoptions(precision=8)

hf_token = "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"
login(hf_token)
checkpoint = "meta-llama/Llama-3.2-11B-Vision"
processor = AutoProcessor.from_pretrained(checkpoint)
url = "https://huggingface.co/datasets/huggingface/documentation-images/resolve/0052a70beed5bf71b92610a43a52df6d286cd5f3/diffusers/rabbit.jpg"
image = Image.open(requests.get(url, stream=True).raw)
inputs_torch = processor(images=image, return_tensors="pt")
inputs_jax = processor(images=image, return_tensors="jax")

In [14]:
import torch.nn as nn
import torch
class TorchConv(nn.Module):
    def __init__(self, dtype=torch.bfloat16):
        super(TorchConv, self).__init__()
        self.patch_embedding = nn.Conv2d(
            in_channels=3, #3
            out_channels=1280, #1280
            kernel_size=14, #14
            stride=14, #14
            padding="valid",
            bias=False,
            dtype=dtype,
        )
        self.dtype = dtype

    def forward(
        self,
        pixel_values: torch.Tensor,

    ):
        batch_size, num_concurrent_media, num_tiles, num_channels, height, width = pixel_values.shape #(1, 1, 4, 3, 448, 448)

        pixel_values = pixel_values.reshape(batch_size * num_concurrent_media * num_tiles, num_channels, height, width) #(4, 3, 448, 448)
        # Patch embedding
        patch_embeds = self.patch_embedding(pixel_values.to(torch.bfloat16).to('cuda')) # (batch_size * num_concurrent_media * num_tiles, hidden_size=1280, 32, 32)
        return patch_embeds


# Initialize the model
torch_model = TorchConv(dtype=torch.bfloat16).to('cuda')


# Get the parameters from the TorchConv model
torch_params = torch_model.patch_embedding.weight
# # Example PyTorch tensor
# torch_params_32 = torch.randn(torch_params.shape, dtype=torch.float32)

# # Permute the tensor's dimensions
# torch_params_permuted = torch_params_32.permute(2, 3, 1, 0)

# # Convert the PyTorch tensor to a NumPy array
# torch_params_numpy = torch_params_permuted.detach().cpu().numpy()

# # Convert the NumPy array to a JAX tensor with dtype bfloat16
# jax_params = jnp.array(torch_params_numpy, dtype=jnp.bfloat16)
# torch_params = torch.tensor(torch_params_32, dtype=torch.bfloat16)
# torch_params = torch.nn.Parameter(torch.tensor(torch_params_32, dtype=torch.bfloat16, device='cuda'))
# torch_model.patch_embedding.weight = torch_params
torch_model.patch_embedding.weight = model_torch.patch_embedding.weight
# Perform a forward pass through the model
output_torch = torch_model(inputs_torch.pixel_values)

RuntimeError: Input type (CUDABFloat16Type) and weight type (CPUBFloat16Type) should be the same

In [ ]:
from flax.core import freeze, unfreeze
from flax import linen as fnn
class JaxConv(fnn.Module):
  dtype: jnp.dtype = jnp.bfloat16

  def setup(self):

    self.patch_embedding = fnn.Conv(
        1280,
        kernel_size=(14, 14),
        strides=(14, 14),
        padding="VALID",
        use_bias=False,
        dtype=self.dtype,
        kernel_init=jax.nn.initializers.normal(),
    )
 
  def __call__(
      self,
      pixel_values: jnp.ndarray,
  ):
        batch_size, num_concurrent_media, num_tiles, num_channels, height, width = pixel_values.shape

        pixel_values = pixel_values.reshape((batch_size * num_concurrent_media * num_tiles, num_channels, height, width))

        # Patch embedding
        patch_embeds = self.patch_embedding(pixel_values.transpose((0, 2, 3, 1)))

        patch_embeds = patch_embeds.transpose((0, 3, 1, 2))

        return patch_embeds
        
# Initialize the model
flax_model = JaxConv()
# Initialize parameters
params = flax_model.init(jax.random.PRNGKey(0), jnp.ones((1, 1, 4, 3, 448, 448)))

# # Convert PyTorch parameters to JAX parameters
params = unfreeze(params)
params['params']['patch_embedding']['kernel'] = model.params['vision_model']['patch_embedding']['kernel']
params = freeze(params)


In [56]:
output_jax = flax_model.apply(params, inputs_jax.pixel_values)

In [57]:
output_jax

Array([[[[60.75, 61, 60, ..., 59.5, 59.25, 42.5],
         [24.875, 45.75, 52.25, ..., 59.25, 59, 57],
         [-23.25, -6.6875, 3.20312, ..., 59, 60, 59],
         ...,
         [-1.91406, 9.5625, 13.9375, ..., -7.96875, 29.875, 47.25],
         [-16.75, -5.71875, 6.46875, ..., -26.25, -1.64844, 51.5],
         [12.9375, 12.0625, 11.875, ..., -31.125, -23.875, 56.75]],

        [[29, 32.75, 31.625, ..., 30.625, 30.625, 41.25],
         [3.9375, 10.9375, 11.0625, ..., 31.875, 31.75, 28.25],
         [-9.6875, -9.5625, -18.125, ..., 43, 42.25, 40.5],
         ...,
         [-10.5, 3.26562, 15.5, ..., -22, -15.0625, 39.5],
         [11.5, 2.8125, 21, ..., -29.875, -22.5, 42],
         [21, 12.125, 4.9375, ..., -31.125, -31.25, -1.34375]],

        [[2.15625, 4.8125, 5.3125, ..., 4.46875, 4.28125, -7.65625],
         [7.21875, 11, 10.125, ..., 4.53125, 4.09375, 4.5625],
         [-1.67969, -5.8125, 9.0625, ..., 3.375, 5.15625, 3.25],
         ...,
         [6.8125, 8.8125, 3.3125, ..., -

In [58]:
output_torch

tensor([[[[ 6.07500000e+01,  6.10000000e+01,  6.00000000e+01,  ...,
            5.95000000e+01,  5.92500000e+01,  4.25000000e+01],
          [ 2.48750000e+01,  4.57500000e+01,  5.22500000e+01,  ...,
            5.92500000e+01,  5.90000000e+01,  5.70000000e+01],
          [-2.32500000e+01, -6.68750000e+00,  3.20312500e+00,  ...,
            5.90000000e+01,  6.00000000e+01,  5.90000000e+01],
          ...,
          [-1.91406250e+00,  9.56250000e+00,  1.39375000e+01,  ...,
           -7.96875000e+00,  2.98750000e+01,  4.72500000e+01],
          [-1.67500000e+01, -5.71875000e+00,  6.46875000e+00,  ...,
           -2.62500000e+01, -1.64843750e+00,  5.15000000e+01],
          [ 1.29375000e+01,  1.20625000e+01,  1.18750000e+01,  ...,
           -3.11250000e+01, -2.38750000e+01,  5.67500000e+01]],

         [[ 2.90000000e+01,  3.27500000e+01,  3.16250000e+01,  ...,
            3.06250000e+01,  3.06250000e+01,  4.12500000e+01],
          [ 3.93750000e+00,  1.09375000e+01,  1.10625000e+01,  ...

In [15]:
inputs_jax.pixel_values[0,0,0,0,:10,:10]

Array([[1.5507771, 1.5215802, 1.5069818, 1.477785 , 1.4047928, 1.3318007,
        1.2880055, 1.2880055, 1.2296118, 1.1858164],
       [1.477785 , 1.4631865, 1.4339896, 1.3901944, 1.3463992, 1.3026038,
        1.2880055, 1.2880055, 1.2588086, 1.2150133],
       [1.4047928, 1.3901944, 1.3609976, 1.3172023, 1.3026038, 1.2880055,
        1.2880055, 1.2880055, 1.2880055, 1.2588086],
       [1.3172023, 1.3172023, 1.2880055, 1.2442101, 1.2442101, 1.273407 ,
        1.2880055, 1.2880055, 1.3026038, 1.273407 ],
       [1.2442101, 1.2442101, 1.2296118, 1.2150133, 1.2150133, 1.273407 ,
        1.2880055, 1.2880055, 1.3026038, 1.273407 ],
       [1.2296118, 1.2296118, 1.2296118, 1.2296118, 1.2296118, 1.2588086,
        1.273407 , 1.273407 , 1.2880055, 1.273407 ],
       [1.2442101, 1.2442101, 1.2442101, 1.2442101, 1.2442101, 1.2588086,
        1.273407 , 1.273407 , 1.273407 , 1.273407 ],
       [1.2442101, 1.2442101, 1.2442101, 1.2442101, 1.2442101, 1.2588086,
        1.273407 , 1.273407 , 1.27340

In [19]:
model_torch.named_modules()

<generator object Module.named_modules at 0x7fac7c3f45f0>

In [9]:
i = 0
output_torch['last_hidden_state'][:, :, :, 0, i:(i+10)]

tensor([[[[-0.32226562, -1.54687500, -0.07080078,  2.65625000, -1.96875000,
           -0.26757812,  1.64843750,  0.06494141, -1.25781250, -0.38281250],
          [-2.15625000, -1.82812500, -1.27343750,  4.37500000, -2.20312500,
            0.76562500,  1.50781250, -2.01562500, -1.09375000,  1.85937500],
          [-1.47656250, -1.32031250,  1.03906250,  3.12500000, -3.73437500,
            5.81250000,  1.79687500, -1.52343750, -0.56250000,  1.82812500],
          [ 0.77343750,  0.92968750,  0.69140625,  0.15625000,  0.18457031,
            1.25000000,  0.02075195,  0.37109375,  1.49218750,  1.41406250]]]],
       dtype=torch.bfloat16, grad_fn=<SliceBackward0>)

In [10]:
output_jax1['last_hidden_state'][:, :, :, 0, i:(i+10)]

Array([[[[5.65625, -5.25, -5.375, 5.8125, 4.90625, -4.21875, 1.55469,
          -3.15625, 0.984375, 3.90625],
         [6.34375, -3.03125, -6.4375, 6.03125, 7.8125, -3.59375,
          2.48438, -7.15625, -0.753906, 4.1875],
         [14, -4.09375, -7.625, 2.76562, 11.8125, -10.5, 0.722656,
          -6.59375, 0.808594, 5.59375],
         [4.21875, 3.5, -2.51562, -3.89062, -1.25, 0.566406, 4.65625,
          2.09375, 8.8125, 4.5625]]]], dtype=bfloat16)

In [11]:
output_jax2['last_hidden_state'][:, :, :, 0, i:(i+10)]

Array([[[[5.65625, -5.25, -5.375, 5.8125, 4.90625, -4.21875, 1.55469,
          -3.15625, 0.984375, 3.90625],
         [6.34375, -3.03125, -6.4375, 6.03125, 7.8125, -3.59375,
          2.48438, -7.15625, -0.753906, 4.1875],
         [14, -4.09375, -7.625, 2.76562, 11.8125, -10.5, 0.722656,
          -6.59375, 0.808594, 5.59375],
         [4.21875, 3.5, -2.51562, -3.89062, -1.25, 0.566406, 4.65625,
          2.09375, 8.8125, 4.5625]]]], dtype=bfloat16)

In [ ]:
from jax import tree_util

def print_detailed_info(name, param):
    print(f"{name}   {param.shape}; {param.dtype}")

tree_util.tree_map_with_path(
    lambda path, x: print_detailed_info("".join(str(p) for p in path), x),
    model.params
)

In [ ]:
for name, param in model_torch.named_parameters():
    print(f"[\"{name}\"]   {param.shape}; {param.dtype}")

In [ ]:
model_torch.state_dict()["transformer.layers.31.self_attn.q_proj.weight"] 

In [ ]:
model.params['vision_model']['transformer']['layers.31']['self_attn']['q_proj']['kernel']

In [ ]:
inputs_jax['pixel_values'].shape

In [ ]:
inputs_jax['pixel_values'].shape