In [1]:
from transformers import MllamaVisionModel, FlaxMllamaVisionModel
from transformers import AutoProcessor, MllamaTextModel
import requests
import torch
import jax
import jax.numpy as jnp
from PIL import Image
from huggingface_hub import login
torch.set_printoptions(precision=8)
jax.numpy.set_printoptions(precision=10)

hf_token = "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"
login(hf_token)
checkpoint = "meta-llama/Llama-3.2-11B-Vision"
processor = AutoProcessor.from_pretrained(checkpoint)
url = "https://huggingface.co/datasets/huggingface/documentation-images/resolve/0052a70beed5bf71b92610a43a52df6d286cd5f3/diffusers/rabbit.jpg"
image = Image.open(requests.get(url, stream=True).raw)

model_torch = MllamaVisionModel.from_pretrained(checkpoint, torch_dtype=torch.bfloat16).to("cuda")

model = FlaxMllamaVisionModel.from_pretrained("/home/amd/model/hub/models--meta-llama--Llama-3.2-11B-Vision/pytorch", from_pt=True, dtype=jnp.bfloat16)

/opt/conda/envs/py_3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Using the `SDPA` attention implementation on multi-gpu setup with ROCM may lead to performance issues due to the FA backend. Disabling it to use alternative backends.
Loading checkpoint shards: 100%|██████████| 5/5 [00:00<00:00,  6.54it/s]
E1123 06:34:49.478979 1227008 buffer_comparator.cc:157] Difference at 19685: -inf, expected -2.88442e+38
E1123 06:34:49.479017 1227008 buffer_comparator.cc:157] Difference at 20777: -inf, expected -3.37624e+38
E1123 06:34:49.479020 1227008 buffer_comparator.cc:157] Difference at 20867: 2.96418e+38, expected inf
E1123 06:34:49.479023 1227008 buffer_comparator.cc:157] Difference at 20965: -inf, expected -3.04393e+38
E1123 06:34:49.479025 1227008 buffer_comparator.cc:157] Difference at 21049: 2.89772

jax (1, 16, 4128, 80) [[[[-0.0110474 0.0098877 -0.00263977 ... 0.00250244 0.00494385
    0.00921631]
   [-0.00952148 0.00546265 -0.00234985 ... 0.00576782 0.00382996
    0.00604248]
   [-0.00306702 0.00518799 -0.00273132 ... 0.00534058 0.00494385
    0.00442505]
   ...
   [-0.00772095 0.00759888 -0.00427246 ... 0.00408936 0.00500488
    0.00619507]
   [-0.00772095 0.00759888 -0.00427246 ... 0.00408936 0.00500488
    0.00619507]
   [-0.00772095 0.00759888 -0.00427246 ... 0.00408936 0.00500488
    0.00619507]]

  [[-0.00238037 -0.00210571 -0.00146484 ... -0.00537109 0.000759125
    -0.00976562]
   [-0.00270081 -0.00331116 0.000123024 ... -0.00650024 0.00189972
    -0.00939941]
   [-0.00314331 0.00108337 -0.00338745 ... -0.00836182 0.000213623
    -0.00836182]
   ...
   [-0.00332642 -6.58035e-05 -0.00148773 ... -0.00549316 0.000720978
    -0.00720215]
   [-0.00332642 -6.58035e-05 -0.00148773 ... -0.00549316 0.000720978
    -0.00720215]
   [-0.00332642 -6.58035e-05 -0.00148773 ... -0.00549

Some weights of the model checkpoint at /home/amd/model/hub/models--meta-llama--Llama-3.2-11B-Vision/pytorch were not used when initializing FlaxMllamaVisionModel: {('language_model', 'model', 'layers.3', 'cross_attn', 'v_proj', 'kernel'), ('language_model', 'model', 'layers.25', 'input_layernorm', 'kernel'), ('language_model', 'model', 'layers.37', 'input_layernorm', 'kernel'), ('language_model', 'model', 'layers.10', 'self_attn', 'k_proj', 'kernel'), ('language_model', 'model', 'layers.10', 'input_layernorm', 'kernel'), ('language_model', 'model', 'layers.38', 'cross_attn_mlp_gate'), ('language_model', 'model', 'layers.9', 'mlp', 'down_proj', 'kernel'), ('language_model', 'model', 'layers.8', 'post_attention_layernorm', 'kernel'), ('language_model', 'model', 'layers.29', 'self_attn', 'o_proj', 'kernel'), ('language_model', 'model', 'layers.7', 'self_attn', 'q_proj', 'kernel'), ('language_model', 'model', 'layers.32', 'mlp', 'down_proj', 'kernel'), ('language_model', 'model', 'layers.

In [2]:
inputs_jax = processor(images=image, return_tensors="jax")
inputs = processor(images=image, return_tensors="pt").to("cuda")
output_torch = model_torch(**inputs)

torch torch.Size([1, 16, 4128, 80]) tensor([[[[-0.01129150,  0.20898438, -0.00903320,  ...,  0.02868652,
            0.01806641, -0.01214600],
          [ 0.00625610, -0.13867188, -0.14453125,  ..., -0.03320312,
            0.05004883, -0.03344727],
          [ 0.01037598, -0.17968750, -0.16015625,  ..., -0.05517578,
            0.05029297, -0.02600098],
          ...,
          [ 0.06591797,  0.39843750,  0.00059128,  ..., -0.02258301,
            0.03051758,  0.05908203],
          [ 0.06591797,  0.39843750,  0.00059128,  ..., -0.02258301,
            0.03051758,  0.05908203],
          [ 0.06591797,  0.39843750,  0.00059128,  ..., -0.02258301,
            0.03051758,  0.05908203]],

         [[-0.00714111,  0.04467773,  0.02416992,  ..., -0.01525879,
           -0.00212097,  0.03271484],
          [ 0.00133514,  0.05395508,  0.03759766,  ..., -0.00503540,
           -0.12011719,  0.06152344],
          [ 0.00354004,  0.05493164,  0.03759766,  ..., -0.00285339,
           -0.12792969

In [3]:
output_jax = model(**inputs_jax)

jax (1, 16, 4128, 80) [[[[-0.0112305 0.208984 -0.0090332 ... 0.0286865 0.0180664 -0.0120239]
   [0.00622559 -0.137695 -0.143555 ... -0.0332031 0.0495605 -0.0332031]
   [0.010437 -0.179688 -0.160156 ... -0.0554199 0.050293 -0.026123]
   ...
   [0.0664062 0.398438 0.000583649 ... -0.0228271 0.0305176 0.0593262]
   [0.0664062 0.398438 0.000583649 ... -0.0228271 0.0305176 0.0593262]
   [0.0664062 0.398438 0.000583649 ... -0.0228271 0.0305176 0.0593262]]

  [[-0.00735474 0.0449219 0.0239258 ... -0.0154419 -0.00366211
    0.0332031]
   [0.00139618 0.0539551 0.0375977 ... -0.00506592 -0.120117 0.0615234]
   [0.00346375 0.0551758 0.0375977 ... -0.0027771 -0.126953 0.0639648]
   ...
   [0.00352478 0.0341797 0.0249023 ... -0.0183105 0.101562 0.00848389]
   [0.00352478 0.0341797 0.0249023 ... -0.0183105 0.101562 0.00848389]
   [0.00352478 0.0341797 0.0249023 ... -0.0183105 0.101562 0.00848389]]

  [[-0.137695 0.0132446 0.0234375 ... -0.015625 -0.0159912 -0.107422]
   [-0.139648 0.00701904 0.01721

In [8]:
inputs['aspect_ratio_mask']

tensor([[[1, 1, 1, 1]]], device='cuda:0')

In [3]:
output_torch.last_hidden_state[0,0,0,0,-10:]

tensor([-0.53125000,  0.47265625, -0.35742188,  0.23925781, -2.00000000,
        -0.24902344,  0.36718750, -0.90625000, -2.68750000, -4.12500000],
       device='cuda:0', dtype=torch.bfloat16, grad_fn=<SliceBackward0>)

In [4]:
output_jax.last_hidden_state[0,0,0,0,-10:]

Array([-0.554688, 0.332031, -0.0800781, 4.34375, 7.125, -0.386719,
       0.636719, -0.601562, -0.289062, -0.617188], dtype=bfloat16)

In [5]:
from transformers import MllamaVisionModel, FlaxMllamaVisionModel
from transformers import AutoProcessor, MllamaTextModel
import requests
import torch
import jax
import jax.numpy as jnp
from PIL import Image
from huggingface_hub import login
torch.set_printoptions(precision=8)

hf_token = "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"
login(hf_token)
checkpoint = "meta-llama/Llama-3.2-11B-Vision"
processor = AutoProcessor.from_pretrained(checkpoint)
url = "https://huggingface.co/datasets/huggingface/documentation-images/resolve/0052a70beed5bf71b92610a43a52df6d286cd5f3/diffusers/rabbit.jpg"
image = Image.open(requests.get(url, stream=True).raw)
inputs_torch = processor(images=image, return_tensors="pt")
inputs_jax = processor(images=image, return_tensors="jax")

In [6]:
import torch.nn as nn
import torch
class TorchConv(nn.Module):
    def __init__(self, dtype=torch.bfloat16):
        super(TorchConv, self).__init__()
        self.patch_embedding = nn.Conv2d(
            in_channels=3, #3
            out_channels=1280, #1280
            kernel_size=14, #14
            stride=14, #14
            padding="valid",
            bias=False,
            dtype=dtype,
        )
        self.dtype = dtype

    def forward(
        self,
        pixel_values: torch.Tensor,

    ):
        batch_size, num_concurrent_media, num_tiles, num_channels, height, width = pixel_values.shape #(1, 1, 4, 3, 448, 448)

        pixel_values = pixel_values.reshape(batch_size * num_concurrent_media * num_tiles, num_channels, height, width) #(4, 3, 448, 448)
        # Patch embedding
        patch_embeds = self.patch_embedding(pixel_values.to(torch.bfloat16).to('cuda')) # (batch_size * num_concurrent_media * num_tiles, hidden_size=1280, 32, 32)
        return patch_embeds


# Initialize the model
torch_model = TorchConv(dtype=torch.bfloat16).to('cuda')


# Get the parameters from the TorchConv model
torch_params = torch_model.patch_embedding.weight
# # Example PyTorch tensor
# torch_params_32 = torch.randn(torch_params.shape, dtype=torch.float32)

# # Permute the tensor's dimensions
# torch_params_permuted = torch_params_32.permute(2, 3, 1, 0)

# # Convert the PyTorch tensor to a NumPy array
# torch_params_numpy = torch_params_permuted.detach().cpu().numpy()

# # Convert the NumPy array to a JAX tensor with dtype bfloat16
# jax_params = jnp.array(torch_params_numpy, dtype=jnp.bfloat16)
# torch_params = torch.tensor(torch_params_32, dtype=torch.bfloat16)
# torch_params = torch.nn.Parameter(torch.tensor(torch_params_32, dtype=torch.bfloat16, device='cuda'))
# torch_model.patch_embedding.weight = torch_params
torch_model.patch_embedding.weight = model_torch.patch_embedding.weight
# Perform a forward pass through the model
output_torch = torch_model(inputs_torch.pixel_values)

In [7]:
from flax.core import freeze, unfreeze
from flax import linen as fnn
class JaxConv(fnn.Module):
  dtype: jnp.dtype = jnp.bfloat16

  def setup(self):

    self.patch_embedding = fnn.Conv(
        1280,
        kernel_size=(14, 14),
        strides=(14, 14),
        padding="VALID",
        use_bias=False,
        dtype=self.dtype,
        kernel_init=jax.nn.initializers.normal(),
    )
 
  def __call__(
      self,
      pixel_values: jnp.ndarray,
  ):
        batch_size, num_concurrent_media, num_tiles, num_channels, height, width = pixel_values.shape

        pixel_values = pixel_values.reshape((batch_size * num_concurrent_media * num_tiles, num_channels, height, width))

        # Patch embedding
        patch_embeds = self.patch_embedding(pixel_values.transpose((0, 2, 3, 1)))

        patch_embeds = patch_embeds.transpose((0, 3, 1, 2))

        return patch_embeds
        
# Initialize the model
flax_model = JaxConv()
# Initialize parameters
params = flax_model.init(jax.random.PRNGKey(0), jnp.ones((1, 1, 4, 3, 448, 448)))

# # Convert PyTorch parameters to JAX parameters
params = unfreeze(params)
params['params']['patch_embedding']['kernel'] = model.params['vision_model']['patch_embedding']['kernel']
params = freeze(params)


In [8]:
output_jax = flax_model.apply(params, inputs_jax.pixel_values)

In [9]:
output_jax

Array([[[[-0.191406, -0.176758, -0.185547, ..., -0.175781, -0.174805,
          -0.0688477],
         [0.00186157, -0.0678711, -0.234375, ..., -0.175781, -0.172852,
          -0.170898],
         [0.0534668, 0.114258, 0.0119629, ..., -0.203125, -0.191406,
          -0.192383],
         ...,
         [0.0219727, 0.0603027, 0.0556641, ..., -0.0135498, -0.0859375,
          -0.121582],
         [0.034668, 0.103516, 0.032959, ..., 0.00430298, 0.010376,
          -0.111328],
         [0.0181885, 0.0126953, 0.00482178, ..., 0.0419922, 0.0241699,
          -0.0947266]],

        [[0.0412598, 0.0356445, 0.0444336, ..., 0.0368652, 0.0410156,
          0.176758],
         [0.12207, 0.0373535, 0.090332, ..., 0.0291748, 0.0358887,
          0.0664062],
         [-0.0280762, 0.0534668, -0.0334473, ..., 0.0456543, 0.0317383,
          0.0152588],
         ...,
         [-0.0566406, 0.0668945, 0.0385742, ..., 0.0158691, -0.022583,
          0.0622559],
         [0.0108032, 0.0429688, 0.0495605, ..., 

In [10]:
output_torch

tensor([[[[-1.91406250e-01, -1.76757812e-01, -1.85546875e-01,  ...,
           -1.75781250e-01, -1.74804688e-01, -6.88476562e-02],
          [ 1.86157227e-03, -6.78710938e-02, -2.34375000e-01,  ...,
           -1.75781250e-01, -1.72851562e-01, -1.70898438e-01],
          [ 5.34667969e-02,  1.14257812e-01,  1.19628906e-02,  ...,
           -2.03125000e-01, -1.91406250e-01, -1.92382812e-01],
          ...,
          [ 2.19726562e-02,  6.03027344e-02,  5.56640625e-02,  ...,
           -1.35498047e-02, -8.59375000e-02, -1.21582031e-01],
          [ 3.46679688e-02,  1.03515625e-01,  3.29589844e-02,  ...,
            4.30297852e-03,  1.03759766e-02, -1.11328125e-01],
          [ 1.81884766e-02,  1.26953125e-02,  4.82177734e-03,  ...,
            4.19921875e-02,  2.41699219e-02, -9.47265625e-02]],

         [[ 4.12597656e-02,  3.56445312e-02,  4.44335938e-02,  ...,
            3.68652344e-02,  4.10156250e-02,  1.76757812e-01],
          [ 1.22070312e-01,  3.73535156e-02,  9.03320312e-02,  ...

In [11]:
inputs_jax.pixel_values[0,0,0,0,:10,:10]

Array([[1.5507771, 1.477785 , 1.4047928, 1.3172023, 1.2442101, 1.2296118,
        1.2442101, 1.2442101, 1.273407 , 1.273407 ],
       [1.5215802, 1.4631865, 1.3901944, 1.3172023, 1.2442101, 1.2296118,
        1.2442101, 1.2442101, 1.273407 , 1.273407 ],
       [1.5069818, 1.4339896, 1.3609976, 1.2880055, 1.2296118, 1.2296118,
        1.2442101, 1.2442101, 1.273407 , 1.273407 ],
       [1.477785 , 1.3901944, 1.3172023, 1.2442101, 1.2150133, 1.2296118,
        1.2442101, 1.2442101, 1.273407 , 1.273407 ],
       [1.4047928, 1.3463992, 1.3026038, 1.2442101, 1.2150133, 1.2296118,
        1.2442101, 1.2442101, 1.273407 , 1.273407 ],
       [1.3318007, 1.3026038, 1.2880055, 1.273407 , 1.273407 , 1.2588086,
        1.2588086, 1.2588086, 1.2880055, 1.2880055],
       [1.2880055, 1.2880055, 1.2880055, 1.2880055, 1.2880055, 1.273407 ,
        1.273407 , 1.273407 , 1.2880055, 1.2880055],
       [1.2880055, 1.2880055, 1.2880055, 1.2880055, 1.2880055, 1.273407 ,
        1.273407 , 1.273407 , 1.28800

In [12]:
model_torch.named_modules()

<generator object Module.named_modules at 0x7ef9b8d478b0>

In [13]:
i = 0
output_torch['last_hidden_state'][:, :, :, 0, i:(i+10)]

IndexError: too many indices for tensor of dimension 4

In [ ]:
output_jax1['last_hidden_state'][:, :, :, 0, i:(i+10)]

Array([[[[5.65625, -5.25, -5.375, 5.8125, 4.90625, -4.21875, 1.55469,
          -3.15625, 0.984375, 3.90625],
         [6.34375, -3.03125, -6.4375, 6.03125, 7.8125, -3.59375,
          2.48438, -7.15625, -0.753906, 4.1875],
         [14, -4.09375, -7.625, 2.76562, 11.8125, -10.5, 0.722656,
          -6.59375, 0.808594, 5.59375],
         [4.21875, 3.5, -2.51562, -3.89062, -1.25, 0.566406, 4.65625,
          2.09375, 8.8125, 4.5625]]]], dtype=bfloat16)

In [ ]:
output_jax2['last_hidden_state'][:, :, :, 0, i:(i+10)]

Array([[[[5.65625, -5.25, -5.375, 5.8125, 4.90625, -4.21875, 1.55469,
          -3.15625, 0.984375, 3.90625],
         [6.34375, -3.03125, -6.4375, 6.03125, 7.8125, -3.59375,
          2.48438, -7.15625, -0.753906, 4.1875],
         [14, -4.09375, -7.625, 2.76562, 11.8125, -10.5, 0.722656,
          -6.59375, 0.808594, 5.59375],
         [4.21875, 3.5, -2.51562, -3.89062, -1.25, 0.566406, 4.65625,
          2.09375, 8.8125, 4.5625]]]], dtype=bfloat16)

In [ ]:
from jax import tree_util

def print_detailed_info(name, param):
    print(f"{name}   {param.shape}; {param.dtype}")

tree_util.tree_map_with_path(
    lambda path, x: print_detailed_info("".join(str(p) for p in path), x),
    model.params
)

In [ ]:
for name, param in model_torch.named_parameters():
    print(f"[\"{name}\"]   {param.shape}; {param.dtype}")

In [ ]:
model_torch.state_dict()["transformer.layers.31.self_attn.q_proj.weight"] 

In [ ]:
model.params['vision_model']['transformer']['layers.31']['self_attn']['q_proj']['kernel']

In [ ]:
inputs_jax['pixel_values'].shape

In [ ]:
inputs_jax['pixel_values'].shape