In [1]:
from transformers import MllamaVisionModel, FlaxMllamaVisionModel
from transformers import AutoProcessor, MllamaTextModel
import requests
import torch
import jax
import jax.numpy as jnp
from PIL import Image
from huggingface_hub import login
torch.set_printoptions(precision=8)

hf_token = "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"
login(hf_token)
checkpoint = "meta-llama/Llama-3.2-11B-Vision"
processor = AutoProcessor.from_pretrained(checkpoint)
url = "https://huggingface.co/datasets/huggingface/documentation-images/resolve/0052a70beed5bf71b92610a43a52df6d286cd5f3/diffusers/rabbit.jpg"
image = Image.open(requests.get(url, stream=True).raw)

model_torch = MllamaVisionModel.from_pretrained(checkpoint, torch_dtype=torch.bfloat16).to("cuda")

model = FlaxMllamaVisionModel.from_pretrained("/home/amd/model/hub/models--meta-llama--Llama-3.2-11B-Vision/pytorch", from_pt=True, dtype=jnp.bfloat16)

/opt/conda/envs/py_3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Using the `SDPA` attention implementation on multi-gpu setup with ROCM may lead to performance issues due to the FA backend. Disabling it to use alternative backends.
Loading checkpoint shards: 100%|██████████| 5/5 [00:00<00:00,  7.15it/s]
E1123 01:09:23.771134 1124874 buffer_comparator.cc:157] Difference at 19685: -inf, expected -2.88442e+38
E1123 01:09:23.771169 1124874 buffer_comparator.cc:157] Difference at 20777: -inf, expected -3.37624e+38
E1123 01:09:23.771173 1124874 buffer_comparator.cc:157] Difference at 20867: 2.96418e+38, expected inf
E1123 01:09:23.771175 1124874 buffer_comparator.cc:157] Difference at 20965: -inf, expected -3.04393e+38
E1123 01:09:23.771178 1124874 buffer_comparator.cc:157] Difference at 21049: 2.89772

jax (1, 4128, 1280) [[[-0.00772095 0.00759888 -0.00427246 ... 0.0032959 0.00306702
   0.00309753]
  [-0.00772095 0.00759888 -0.00427246 ... 0.0032959 0.00306702
   0.00309753]
  [-0.00772095 0.00759888 -0.00427246 ... 0.0032959 0.00306702
   0.00309753]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
jax (1, 4128, 1280) [[[-0.0122681 0.00518799 0.000192642 ... -0.00994873 -0.00390625
   0.0272217]
  [-0.0122681 0.00518799 0.000192642 ... -0.00994873 -0.00390625
   0.0272217]
  [-0.0122681 0.00518799 0.000192642 ... -0.00994873 -0.00390625
   0.0272217]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
jax (1, 4128, 1280) [[[0.012207 0.0045166 -0.0238037 ... -0.00436401 0.0118408 -0.0065918]
  [0.012207 0.0045166 -0.0238037 ... -0.00436401 0.0118408 -0.0065918]
  [0.012207 0.0045166 -0.0238037 ... -0.00436401 0.0118408 -0.0065918]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
jax (1, 4128, 1280) [[[-0.0356445 -0.00123596 -0.032

Some weights of the model checkpoint at /home/amd/model/hub/models--meta-llama--Llama-3.2-11B-Vision/pytorch were not used when initializing FlaxMllamaVisionModel: {('language_model', 'model', 'layers.19', 'self_attn', 'v_proj', 'kernel'), ('language_model', 'model', 'layers.30', 'mlp', 'gate_proj', 'kernel'), ('language_model', 'model', 'norm', 'kernel'), ('language_model', 'model', 'layers.25', 'input_layernorm', 'kernel'), ('language_model', 'model', 'layers.10', 'post_attention_layernorm', 'kernel'), ('language_model', 'model', 'layers.38', 'mlp', 'gate_proj', 'kernel'), ('language_model', 'model', 'layers.29', 'self_attn', 'v_proj', 'kernel'), ('language_model', 'model', 'layers.4', 'mlp', 'up_proj', 'kernel'), ('language_model', 'model', 'layers.23', 'cross_attn', 'q_norm', 'kernel'), ('language_model', 'model', 'layers.38', 'mlp', 'up_proj', 'kernel'), ('language_model', 'model', 'layers.32', 'self_attn', 'q_proj', 'kernel'), ('language_model', 'model', 'layers.28', 'cross_attn_

In [2]:
inputs_jax = processor(images=image, return_tensors="jax")
inputs = processor(images=image, return_tensors="pt").to("cuda")
output_torch = model_torch(**inputs)

torch torch.Size([1, 4128, 1280]) tensor([[[-0.01129150,  0.20898438, -0.00903320,  ...,  0.01782227,
          -0.02978516,  0.01867676],
         [ 0.00625610, -0.13867188, -0.14453125,  ...,  0.13671875,
           0.06542969, -0.11523438],
         [ 0.01037598, -0.17968750, -0.16015625,  ...,  0.11279297,
           0.13476562, -0.14062500],
         ...,
         [ 0.48242188,  1.35937500,  0.06054688,  ...,  0.05908203,
           0.37109375,  0.16894531],
         [ 0.48242188,  1.35937500,  0.06054688,  ...,  0.05908203,
           0.37109375,  0.16894531],
         [ 0.48242188,  1.35937500,  0.06054688,  ...,  0.05908203,
           0.37109375,  0.16894531]]], device='cuda:0', dtype=torch.bfloat16,
       grad_fn=<ViewBackward0>)
torch torch.Size([1, 4128, 1280]) tensor([[[ 0.02478027,  0.06835938, -0.05004883,  ..., -0.05908203,
           0.05419922,  0.03247070],
         [ 0.03198242,  0.05883789, -0.02478027,  ...,  0.13964844,
           0.05859375, -0.06884766],
     

In [3]:
output_jax = model(**inputs_jax)

jax (1, 4128, 1280) [[[-0.0703125 -0.210938 0.0288086 ... 0.000736237 0.0216064 0.103516]
  [-0.0703125 -0.210938 0.0288086 ... 0.000736237 0.0216064 0.103516]
  [-0.0703125 -0.210938 0.0288086 ... 0.000736237 0.0216064 0.103516]
  ...
  [-0.081543 0.057373 -0.0206299 ... -0.0693359 -0.0205078 -0.0324707]
  [-0.081543 0.057373 -0.0206299 ... -0.0693359 -0.0205078 -0.0324707]
  [-0.081543 0.057373 -0.0206299 ... -0.0693359 -0.0205078 -0.0324707]]]
jax (1, 4128, 1280) [[[-0.00202942 0.269531 0.00460815 ... -0.0737305 -0.090332 0.0142212]
  [-0.00202942 0.269531 0.00460815 ... -0.0737305 -0.090332 0.0142212]
  [-0.00202942 0.269531 0.00460815 ... -0.0737305 -0.090332 0.0142212]
  ...
  [-0.123047 -0.425781 0.566406 ... -0.139648 0.236328 0.181641]
  [-0.123047 -0.425781 0.566406 ... -0.139648 0.236328 0.181641]
  [-0.123047 -0.425781 0.566406 ... -0.139648 0.236328 0.181641]]]
jax (1, 4128, 1280) [[[-0.142578 -0.0090332 0.0158691 ... -0.0311279 0.0133057 -0.0217285]
  [-0.142578 -0.009033

In [3]:
output_torch.last_hidden_state[0,0,0,0,-10:]

tensor([-0.53125000,  0.47265625, -0.35742188,  0.23925781, -2.00000000,
        -0.24902344,  0.36718750, -0.90625000, -2.68750000, -4.12500000],
       device='cuda:0', dtype=torch.bfloat16, grad_fn=<SliceBackward0>)

In [4]:
output_jax.last_hidden_state[0,0,0,0,-10:]

Array([-0.554688, 0.332031, -0.0800781, 4.34375, 7.125, -0.386719,
       0.636719, -0.601562, -0.289062, -0.617188], dtype=bfloat16)

In [5]:
from transformers import MllamaVisionModel, FlaxMllamaVisionModel
from transformers import AutoProcessor, MllamaTextModel
import requests
import torch
import jax
import jax.numpy as jnp
from PIL import Image
from huggingface_hub import login
torch.set_printoptions(precision=8)

hf_token = "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"
login(hf_token)
checkpoint = "meta-llama/Llama-3.2-11B-Vision"
processor = AutoProcessor.from_pretrained(checkpoint)
url = "https://huggingface.co/datasets/huggingface/documentation-images/resolve/0052a70beed5bf71b92610a43a52df6d286cd5f3/diffusers/rabbit.jpg"
image = Image.open(requests.get(url, stream=True).raw)
inputs_torch = processor(images=image, return_tensors="pt")
inputs_jax = processor(images=image, return_tensors="jax")

In [6]:
import torch.nn as nn
import torch
class TorchConv(nn.Module):
    def __init__(self, dtype=torch.bfloat16):
        super(TorchConv, self).__init__()
        self.patch_embedding = nn.Conv2d(
            in_channels=3, #3
            out_channels=1280, #1280
            kernel_size=14, #14
            stride=14, #14
            padding="valid",
            bias=False,
            dtype=dtype,
        )
        self.dtype = dtype

    def forward(
        self,
        pixel_values: torch.Tensor,

    ):
        batch_size, num_concurrent_media, num_tiles, num_channels, height, width = pixel_values.shape #(1, 1, 4, 3, 448, 448)

        pixel_values = pixel_values.reshape(batch_size * num_concurrent_media * num_tiles, num_channels, height, width) #(4, 3, 448, 448)
        # Patch embedding
        patch_embeds = self.patch_embedding(pixel_values.to(torch.bfloat16).to('cuda')) # (batch_size * num_concurrent_media * num_tiles, hidden_size=1280, 32, 32)
        return patch_embeds


# Initialize the model
torch_model = TorchConv(dtype=torch.bfloat16).to('cuda')


# Get the parameters from the TorchConv model
torch_params = torch_model.patch_embedding.weight
# # Example PyTorch tensor
# torch_params_32 = torch.randn(torch_params.shape, dtype=torch.float32)

# # Permute the tensor's dimensions
# torch_params_permuted = torch_params_32.permute(2, 3, 1, 0)

# # Convert the PyTorch tensor to a NumPy array
# torch_params_numpy = torch_params_permuted.detach().cpu().numpy()

# # Convert the NumPy array to a JAX tensor with dtype bfloat16
# jax_params = jnp.array(torch_params_numpy, dtype=jnp.bfloat16)
# torch_params = torch.tensor(torch_params_32, dtype=torch.bfloat16)
# torch_params = torch.nn.Parameter(torch.tensor(torch_params_32, dtype=torch.bfloat16, device='cuda'))
# torch_model.patch_embedding.weight = torch_params
torch_model.patch_embedding.weight = model_torch.patch_embedding.weight
# Perform a forward pass through the model
output_torch = torch_model(inputs_torch.pixel_values)

In [7]:
from flax.core import freeze, unfreeze
from flax import linen as fnn
class JaxConv(fnn.Module):
  dtype: jnp.dtype = jnp.bfloat16

  def setup(self):

    self.patch_embedding = fnn.Conv(
        1280,
        kernel_size=(14, 14),
        strides=(14, 14),
        padding="VALID",
        use_bias=False,
        dtype=self.dtype,
        kernel_init=jax.nn.initializers.normal(),
    )
 
  def __call__(
      self,
      pixel_values: jnp.ndarray,
  ):
        batch_size, num_concurrent_media, num_tiles, num_channels, height, width = pixel_values.shape

        pixel_values = pixel_values.reshape((batch_size * num_concurrent_media * num_tiles, num_channels, height, width))

        # Patch embedding
        patch_embeds = self.patch_embedding(pixel_values.transpose((0, 2, 3, 1)))

        patch_embeds = patch_embeds.transpose((0, 3, 1, 2))

        return patch_embeds
        
# Initialize the model
flax_model = JaxConv()
# Initialize parameters
params = flax_model.init(jax.random.PRNGKey(0), jnp.ones((1, 1, 4, 3, 448, 448)))

# # Convert PyTorch parameters to JAX parameters
params = unfreeze(params)
params['params']['patch_embedding']['kernel'] = model.params['vision_model']['patch_embedding']['kernel']
params = freeze(params)


In [8]:
output_jax = flax_model.apply(params, inputs_jax.pixel_values)

In [9]:
output_jax

Array([[[[-0.191406, -0.176758, -0.185547, ..., -0.175781, -0.174805,
          -0.0688477],
         [0.00186157, -0.0678711, -0.234375, ..., -0.175781, -0.172852,
          -0.170898],
         [0.0534668, 0.114258, 0.0119629, ..., -0.203125, -0.191406,
          -0.192383],
         ...,
         [0.0219727, 0.0603027, 0.0556641, ..., -0.0135498, -0.0859375,
          -0.121582],
         [0.034668, 0.103516, 0.032959, ..., 0.00430298, 0.010376,
          -0.111328],
         [0.0181885, 0.0126953, 0.00482178, ..., 0.0419922, 0.0241699,
          -0.0947266]],

        [[0.0412598, 0.0356445, 0.0444336, ..., 0.0368652, 0.0410156,
          0.176758],
         [0.12207, 0.0373535, 0.090332, ..., 0.0291748, 0.0358887,
          0.0664062],
         [-0.0280762, 0.0534668, -0.0334473, ..., 0.0456543, 0.0317383,
          0.0152588],
         ...,
         [-0.0566406, 0.0668945, 0.0385742, ..., 0.0158691, -0.022583,
          0.0622559],
         [0.0108032, 0.0429688, 0.0495605, ..., 

In [10]:
output_torch

tensor([[[[-1.91406250e-01, -1.76757812e-01, -1.85546875e-01,  ...,
           -1.75781250e-01, -1.74804688e-01, -6.88476562e-02],
          [ 1.86157227e-03, -6.78710938e-02, -2.34375000e-01,  ...,
           -1.75781250e-01, -1.72851562e-01, -1.70898438e-01],
          [ 5.34667969e-02,  1.14257812e-01,  1.19628906e-02,  ...,
           -2.03125000e-01, -1.91406250e-01, -1.92382812e-01],
          ...,
          [ 2.19726562e-02,  6.03027344e-02,  5.56640625e-02,  ...,
           -1.35498047e-02, -8.59375000e-02, -1.21582031e-01],
          [ 3.46679688e-02,  1.03515625e-01,  3.29589844e-02,  ...,
            4.30297852e-03,  1.03759766e-02, -1.11328125e-01],
          [ 1.81884766e-02,  1.26953125e-02,  4.82177734e-03,  ...,
            4.19921875e-02,  2.41699219e-02, -9.47265625e-02]],

         [[ 4.12597656e-02,  3.56445312e-02,  4.44335938e-02,  ...,
            3.68652344e-02,  4.10156250e-02,  1.76757812e-01],
          [ 1.22070312e-01,  3.73535156e-02,  9.03320312e-02,  ...

In [11]:
inputs_jax.pixel_values[0,0,0,0,:10,:10]

Array([[1.5507771, 1.477785 , 1.4047928, 1.3172023, 1.2442101, 1.2296118,
        1.2442101, 1.2442101, 1.273407 , 1.273407 ],
       [1.5215802, 1.4631865, 1.3901944, 1.3172023, 1.2442101, 1.2296118,
        1.2442101, 1.2442101, 1.273407 , 1.273407 ],
       [1.5069818, 1.4339896, 1.3609976, 1.2880055, 1.2296118, 1.2296118,
        1.2442101, 1.2442101, 1.273407 , 1.273407 ],
       [1.477785 , 1.3901944, 1.3172023, 1.2442101, 1.2150133, 1.2296118,
        1.2442101, 1.2442101, 1.273407 , 1.273407 ],
       [1.4047928, 1.3463992, 1.3026038, 1.2442101, 1.2150133, 1.2296118,
        1.2442101, 1.2442101, 1.273407 , 1.273407 ],
       [1.3318007, 1.3026038, 1.2880055, 1.273407 , 1.273407 , 1.2588086,
        1.2588086, 1.2588086, 1.2880055, 1.2880055],
       [1.2880055, 1.2880055, 1.2880055, 1.2880055, 1.2880055, 1.273407 ,
        1.273407 , 1.273407 , 1.2880055, 1.2880055],
       [1.2880055, 1.2880055, 1.2880055, 1.2880055, 1.2880055, 1.273407 ,
        1.273407 , 1.273407 , 1.28800

In [12]:
model_torch.named_modules()

<generator object Module.named_modules at 0x7ef9b8d478b0>

In [13]:
i = 0
output_torch['last_hidden_state'][:, :, :, 0, i:(i+10)]

IndexError: too many indices for tensor of dimension 4

In [ ]:
output_jax1['last_hidden_state'][:, :, :, 0, i:(i+10)]

Array([[[[5.65625, -5.25, -5.375, 5.8125, 4.90625, -4.21875, 1.55469,
          -3.15625, 0.984375, 3.90625],
         [6.34375, -3.03125, -6.4375, 6.03125, 7.8125, -3.59375,
          2.48438, -7.15625, -0.753906, 4.1875],
         [14, -4.09375, -7.625, 2.76562, 11.8125, -10.5, 0.722656,
          -6.59375, 0.808594, 5.59375],
         [4.21875, 3.5, -2.51562, -3.89062, -1.25, 0.566406, 4.65625,
          2.09375, 8.8125, 4.5625]]]], dtype=bfloat16)

In [ ]:
output_jax2['last_hidden_state'][:, :, :, 0, i:(i+10)]

Array([[[[5.65625, -5.25, -5.375, 5.8125, 4.90625, -4.21875, 1.55469,
          -3.15625, 0.984375, 3.90625],
         [6.34375, -3.03125, -6.4375, 6.03125, 7.8125, -3.59375,
          2.48438, -7.15625, -0.753906, 4.1875],
         [14, -4.09375, -7.625, 2.76562, 11.8125, -10.5, 0.722656,
          -6.59375, 0.808594, 5.59375],
         [4.21875, 3.5, -2.51562, -3.89062, -1.25, 0.566406, 4.65625,
          2.09375, 8.8125, 4.5625]]]], dtype=bfloat16)

In [ ]:
from jax import tree_util

def print_detailed_info(name, param):
    print(f"{name}   {param.shape}; {param.dtype}")

tree_util.tree_map_with_path(
    lambda path, x: print_detailed_info("".join(str(p) for p in path), x),
    model.params
)

In [ ]:
for name, param in model_torch.named_parameters():
    print(f"[\"{name}\"]   {param.shape}; {param.dtype}")

In [ ]:
model_torch.state_dict()["transformer.layers.31.self_attn.q_proj.weight"] 

In [ ]:
model.params['vision_model']['transformer']['layers.31']['self_attn']['q_proj']['kernel']

In [ ]:
inputs_jax['pixel_values'].shape

In [ ]:
inputs_jax['pixel_values'].shape